# Run in background:
# docker compose up -d

name: marketplace-project

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 marketplace-backend marketplace-frontend

  mysql:
    container_name: marketplace-mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "marketplacedb"
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  marketplace-frontend:
    container_name: marketplace-frontend
    image: bryrmiginte/marketplace-frontend:latest
    ports:
      - 5173:5173

  marketplace-backend:
    container_name: marketplace-backend
    image: bryrmiginte/marketplace-backend:latest
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - MARKETPLACE_DB_URL=jdbc:mysql://mysql:3306/marketplacedb
      - MARKETPLACE_DB_USERNAME=${MARKETPLACE_DB_USERNAME}
      - MARKETPLACE_DB_PASSWORD=${MARKETPLACE_DB_PASSWORD}
      - MARKETPLACE_JWT_SECRET=${MARKETPLACE_JWT_SECRET}
